import java.time.LocalDate;
import java.time.format.DateTimeFormatter;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author H4H7X
 */
public class jfrmCalcBasic extends javax.swing.JFrame {
    LocalDate fechaActual = LocalDate.now();
    DateTimeFormatter formato = DateTimeFormatter.ofPattern("EEEE, MMMM, YYYY");
    String fechaFormateada = fechaActual.format(formato);
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(jfrmCalcBasic.class.getName());

    /**
     * Creates new form jfrmCalcBasic
     */
    int valor1 = 0, valor2= 0;
    public jfrmCalcBasic() {
        initComponents();
        jtxtFecha.setText(fechaFormateada);
        this.setLocationRelativeTo(null);
        this.setTitle("Calculadora Básica");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jlblResult = new javax.swing.JLabel();
        jtxtFecha = new javax.swing.JTextField();
        jtxtNum1 = new javax.swing.JTextField();
        jtxtNum2 = new javax.swing.JTextField();
        jbtnNum1 = new javax.swing.JButton();
        jbtnNum2 = new javax.swing.JButton();
        jbtnResta = new javax.swing.JButton();
        jbtnMulti = new javax.swing.JButton();
        jbtnDivi = new javax.swing.JButton();
        jbtnSuma = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 153, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Fecha");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("Digite un Número:");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("Dime otro Número:");

        jlblResult.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jlblResult.setText("Resultado");

        jtxtFecha.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jtxtFecha.setEnabled(false);

        jtxtNum1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jtxtNum1.setText("0");

        jtxtNum2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jtxtNum2.setText("0");

        jbtnNum1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jbtnNum1.setText("+1");
        jbtnNum1.addActionListener(this::jbtnNum1ActionPerformed);

        jbtnNum2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jbtnNum2.setText("+1");
        jbtnNum2.addActionListener(this::jbtnNum2ActionPerformed);

        jbtnResta.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jbtnResta.setText("-");
        jbtnResta.addActionListener(this::jbtnRestaActionPerformed);

        jbtnMulti.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jbtnMulti.setText("*");
        jbtnMulti.addActionListener(this::jbtnMultiActionPerformed);

        jbtnDivi.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jbtnDivi.setText("/");
        jbtnDivi.addActionListener(this::jbtnDiviActionPerformed);

        jbtnSuma.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jbtnSuma.setText("+");
        jbtnSuma.addActionListener(this::jbtnSumaActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtxtNum1)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jbtnNum2, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbtnNum1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlblResult)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(jtxtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jbtnSuma)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jbtnResta)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jbtnMulti)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jbtnDivi)
                                    .addComponent(jtxtNum2))))
                        .addGap(58, 58, 58)))
                .addGap(26, 26, 26))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jtxtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jtxtNum1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnNum1))
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jtxtNum2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnNum2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnSuma)
                    .addComponent(jbtnResta)
                    .addComponent(jbtnMulti)
                    .addComponent(jbtnDivi))
                .addGap(12, 12, 12)
                .addComponent(jlblResult)
                .addContainerGap(57, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnNum1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnNum1ActionPerformed
        // TODO add your handling code here:
        valor1 = Integer.parseInt(jtxtNum1.getText());
        valor1 = valor1+1;
        jtxtNum1.setText(String.valueOf(valor1));
    }//GEN-LAST:event_jbtnNum1ActionPerformed

    private void jbtnNum2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnNum2ActionPerformed
        // TODO add your handling code here:
        valor2 = Integer.parseInt(jtxtNum2.getText());
        valor2 = valor2+1;
        jtxtNum2.setText(String.valueOf(valor2));
    }//GEN-LAST:event_jbtnNum2ActionPerformed

    private void jbtnSumaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnSumaActionPerformed
        // TODO add your handling code here:
        int num1, num2;
        num1 = Integer.parseInt(jtxtNum1.getText());
        num2 = Integer.parseInt(jtxtNum2.getText());
        int suma = num1+num2;
        jlblResult.setText(String.valueOf("Resultado: "+suma));
    }//GEN-LAST:event_jbtnSumaActionPerformed

    private void jbtnRestaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnRestaActionPerformed
        // TODO add your handling code here:
        int num1, num2;
        num1 = Integer.parseInt(jtxtNum1.getText());
        num2 = Integer.parseInt(jtxtNum2.getText());
        int resta = num1-num2;
        jlblResult.setText(String.valueOf("Resultado: "+resta));
    }//GEN-LAST:event_jbtnRestaActionPerformed

    private void jbtnMultiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnMultiActionPerformed
        // TODO add your handling code here:
        int num1, num2;
        num1 = Integer.parseInt(jtxtNum1.getText());
        num2 = Integer.parseInt(jtxtNum2.getText());
        int multi = num1*num2;
        jlblResult.setText(String.valueOf("Resultado: "+multi));
    }//GEN-LAST:event_jbtnMultiActionPerformed

    private void jbtnDiviActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnDiviActionPerformed
        // TODO add your handling code here:
        int num1, num2;
        num1 = Integer.parseInt(jtxtNum1.getText());
        num2 = Integer.parseInt(jtxtNum2.getText());
        int divi = num1/num2;
        jlblResult.setText(String.valueOf("Resultado: "+divi));
    }//GEN-LAST:event_jbtnDiviActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new jfrmCalcBasic().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jbtnDivi;
    private javax.swing.JButton jbtnMulti;
    private javax.swing.JButton jbtnNum1;
    private javax.swing.JButton jbtnNum2;
    private javax.swing.JButton jbtnResta;
    private javax.swing.JButton jbtnSuma;
    private javax.swing.JLabel jlblResult;
    private javax.swing.JTextField jtxtFecha;
    private javax.swing.JTextField jtxtNum1;
    private javax.swing.JTextField jtxtNum2;
    // End of variables declaration//GEN-END:variables
}
